# Local Frontend AI stack
name: local-frontend-ai-stack

services:
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "0.0.0.0:3000:8080"
    environment:
      #OPENAI_API_BASE_URL: "http://host.docker.internal:52625/v1" # FastFlowLM service
      OPENAI_API_BASE_URL: "http://host.docker.internal:8010/v1" # SCAYLE
      OPENAI_API_KEY: "local"
      WEBUI_AUTH: "false"
    volumes:
      - ./data/open-webui/data:/app/backend/data
    # Add custom host entry to allow internal container communication with the host's FastFlowLM service
    extra_hosts:
      - "host.docker.internal:host-gateway"

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: always
    ports:
      - "8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data/searxng/core-config/:/etc/searxng/:rw
      - ./data/searxng/data:/var/cache/searxng/

  valkey:
    container_name: valkey
    image: docker.io/valkey/valkey:9-alpine
    command: valkey-server --save 30 1 --loglevel warning
    volumes:
      - ./data/valkey/data:/data/:rw

  open-terminal:
    image: ghcr.io/open-webui/open-terminal:latest
    container_name: open-terminal
    volumes:
      - /home/egarcia/temp:/home/user
    environment:
      - OPEN_TERMINAL_API_KEY=your-secret-key

  # MCPs
  mcp-time:
    image: mekayelanik/time-mcp:stable
    container_name: mcp-time
    ports:
      - "8060"
    environment:
      - PORT=8060
      - INTERNAL_PORT=38011
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - NODE_ENV=production
      - PROTOCOL=HTTP
      - ENABLE_HTTPS=false
      - HTTP_VERSION_MODE=auto
    hostname: time-mcp
    domainname: local

  mcp-searxng:
    image: isokoliuk/mcp-searxng:latest
    container_name: mcp-searxng
    stdin_open: true
    ports:
      - "3000"
    environment:
      - MCP_HTTP_PORT=3000
      - SEARXNG_URL=http://searxng:8080
